/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form.table;

import java.awt.event.ActionEvent;

/**
 *
 * @author YOGA6
 */
public class PanelAction extends javax.swing.JPanel {

    /**
     * Creates new form PanelAction
     */
    public PanelAction() {
        initComponents();
    }
    public void initEvent(TableActionEvent event, int row) {
        viewbooktitlebutton.addActionListener((ActionEvent ae) -> {
            event.onView(row);
        });
        editbooktitlebutton.addActionListener((ActionEvent ae) -> {
            event.onEdit(row);
        });
       deletebooktitlebutton.addActionListener((ActionEvent ae) -> {
           event.onDelete(row);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewbooktitlebutton = new form.table.ActionButton();
        editbooktitlebutton = new form.table.ActionButton();
        deletebooktitlebutton = new form.table.ActionButton();

        viewbooktitlebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/table/view.png"))); // NOI18N
        viewbooktitlebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbooktitlebuttonActionPerformed(evt);
            }
        });

        editbooktitlebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/table/edit.png"))); // NOI18N

        deletebooktitlebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/table/delete.png"))); // NOI18N
        deletebooktitlebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebooktitlebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewbooktitlebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editbooktitlebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deletebooktitlebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deletebooktitlebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(viewbooktitlebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editbooktitlebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewbooktitlebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbooktitlebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewbooktitlebuttonActionPerformed

    private void deletebooktitlebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebooktitlebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebooktitlebuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private form.table.ActionButton deletebooktitlebutton;
    private form.table.ActionButton editbooktitlebutton;
    private form.table.ActionButton viewbooktitlebutton;
    // End of variables declaration//GEN-END:variables
}
